config/routes.rb
ClickerProject::Application.routes.draw do
  
  match 'questions/list' => 'questions#list'
  match 'responses/list' => 'responses#list'
  resources :questions
  resources :responses
  resources :users

  get "home/index"

  resources :answers
  
  controller :sessions do
    get 'login'   => :new
    post 'login'  => :create
    delete 'logout' => :destroy
  end

  controller :questions do
    get 'list_questions' => :list
  end

  root :to => "questions#index"
end

app/models/question.rb
class Question < ActiveRecord::Base
  QUESTION_TYPES = [ 'multiple choice', 'short answer']
  attr_accessible :question_text, :question_type, :correct_answer, :answer_a, :answer_b, :answer_c, :answer_d
  validates :question_text, :correct_answer, :answer_a, :answer_b, :answer_c, :answer_d, presence: true
  validates :question_type, inclusion: QUESTION_TYPES
  
  has_many :responses
     
  def next
    self.class.find(:first, :conditions => ["id > ?", self.id])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  #before_filter :authorize_admin, only: [:index, :new, :edit, :create, :update, :destroy]
  
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
    @nextquestion = @question.next
    @response = Response.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
  
  def list
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <div class="field">
    <%= f.label :question_type %>
    <%= f.select :question_type, Question::QUESTION_TYPES, prompt: 'Select the type of question' %><br />
  </div>
  <div class="field">
    <%= f.label :question_text %>
    <%= f.text_field :question_text %><br />
  </div>
  <div class="field">
  	<%= f.label "A" %>
  	<%= f.text_field :answer_a %><br />
  	<%= f.label "B" %>
  	<%= f.text_field :answer_b %><br />
  	<%= f.label "C" %>
  	<%= f.text_field :answer_c %><br />
  	<%= f.label "D" %>
  	<%= f.text_field :answer_d %><br />
  </div>
  <div class="field">
  	<%= f.label "Correct Answer:" %><br />
    <%= f.radio_button :correct_answer, 1, :checked => true %>
    <%= f.label "A" %>
    <%= f.radio_button :correct_answer, 2 %>
    <%= f.label "B" %>
    <%= f.radio_button :correct_answer, 3 %>
    <%= f.label "C" %>
    <%= f.radio_button :correct_answer, 4 %>
    <%= f.label "D" %>
  <br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Question text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.question_text %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/list.html.erb
<h2>Listing questions</h2>
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>Question text</th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.question_text %></td>
    <td><%= link_to 'Respond', question %></td>
  </tr>
<% end %>
</table>
<%= link_to 'Show Results', :controller => "responses", :action => "list" %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Question <%= @question.id %> :</strong>
  <%= @question.question_text %>
</p>

<% if @question.question_type == 'multiple choice' %>
	<p>
		A. <%= @question.answer_a %><br />
		B. <%= @question.answer_b %><br />
		C. <%= @question.answer_c %><br />
		D. <%= @question.answer_d %><br />
	</p>
	<%= render :partial => 'responses/form' %>
<% else %>
	<%= render :partial => 'responses/short_answer_form' %>
<% end %>

  

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back to List', questions_path %> |
<% if @nextquestion %>
  <%= link_to 'Next Question', Question.find(@nextquestion.id) %>
<% end %>