config/routes.rb
ClickerProject::Application.routes.draw do
  
  match 'questions/list' => 'questions#list'
  match 'responses/list' => 'responses#list'
  resources :questions
  resources :responses
  resources :users

  get "home/index"

  resources :answers
  
  controller :sessions do
    get 'login'   => :new
    post 'login'  => :create
    delete 'logout' => :destroy
  end

  controller :questions do
    get 'list_questions' => :list
  end

  root :to => "questions#index"
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @responses }
    end
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
    @response = Response.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @response }
    end
  end

  # GET /responses/new
  # GET /responses/new.json
  def new
    @response = Response.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @response }
    end
  end

  # GET /responses/1/edit
  def edit
    @response = Response.find(params[:id])
  end

  # POST /responses
  # POST /responses.json
  def create
    @user = User.find(session[:user_id])
    potential_response = Response.new(params[:response])
    question_id = potential_response.question.id
    count = 0
    
    @user.responses.each do |response|
      if response.question.id == question_id
        count += 1
      end
    end
    
    if count == 0
      @response = @user.responses.build(params[:response])
      respond_to do |format|
        if @response.save
          format.html { redirect_to @response, notice: 'Response was successfully created.' }
          format.json { render json: @response, status: :created, location: @response }
        else
          format.html { render action: "new"}
          format.json { render json: @response.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to list_questions_url, notice: "A response was already created for Question #{question_id}."
    end
  end

  # PUT /responses/1
  # PUT /responses/1.json
  def update
    @response = Response.find(params[:id])

    respond_to do |format|
      if @response.update_attributes(params[:response])
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response = Response.find(params[:id])
    @response.destroy

    respond_to do |format|
      format.html { redirect_to responses_url }
      format.json { head :no_content }
    end
  end
  
  def list
    @responses = Response.all
    @questions = Question.all
    @users = User.all
    @answers = Answer.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @responses }
    end
  end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Choose your response:" %>
    <%= f.radio_button :answer, 1, :checked => true %>
    <%= f.label "A" %>
    <%= f.radio_button :answer, 2 %>
    <%= f.label "B" %>
    <%= f.radio_button :answer, 3 %>
    <%= f.label "C" %>
    <%= f.radio_button :answer, 4 %>
    <%= f.label "D" %>
    <%= f.hidden_field :question_id, :value => @question.id %>
  <br />
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
  
<% end %>

app/views/responses/_short_answer_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  	<%= f.label 'Write Your Answer' %><br />
  	<%= f.text_area :short_answer, row: 5, col: 20  %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
  
<% end %>


app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <tr>
    <th>Question</th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.id %></td>
    <td><%= question.question_text %></td>
  </tr>
<% end %>
</table>

<br />
<table>
  <tr>
    <th>Question</th>
    <th>User</th>
    <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @responses.each do |response| %>
  <tr>
    <td><%= response.question_id %></td>
    <td><%= response.user_id %></td>
    <td><%= response.answer %></td>
    <td><%= link_to 'Show', response %></td>
    <td><%= link_to 'Edit', edit_response_path(response) %></td>
    <td><%= link_to 'Destroy', response, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Response', new_response_path %>

app/views/responses/list.html.erb
<h1>Listing Responses</h1>

<% @questions.each do |question| %>
    <strong>
    <%= question.id %> : <%= question.question_text %>
      <% @a = question.responses.where(answer: '1').count %>
      <% @b = question.responses.where(answer: '2').count %>
      <% @c = question.responses.where(answer: '3').count %>
      <% @d = question.responses.where(answer: '4').count %>

  <div id= "chart<%= question.id %>" style="height:200px; width:600px; "></div>

  <script type="text/javascript">

  $(document).ready(function()
  {
    var bs=  "<%= @a %>";
    //responses = this.getAttribute("theresponses");
    var s1 = ["<%= @a %>", "<%= @b %>", "<%= @c %>", "<%= @d %>"];
    // Can specify a custom tick Array.
    // Ticks should match up one for each y value (category) in the series.
    var ticks = ['A', 'B', 'C', 'D'];
     
    var plot1 = $.jqplot("chart<%= question.id %>", [s1], 
    {
        // The "seriesDefaults" option is an options object that will
        // be applied to all series in the chart.
        seriesDefaults:
        {
            renderer:$.jqplot.BarRenderer,
            rendererOptions: {fillToZero: true}
        },
        /*
        // Custom labels for the series are specified with the "label"
        // option on the series option.  Here a series option object
        // is specified for each series.
        series:[
            {label:'Hotel'},
            {label:'Event Regristration'},
            {label:'Airfare'}
        ],
        // Show the legend and put it outside the grid, but inside the
        // plot container, shrinking the grid to accomodate the legend.
        // A value of "outside" would not shrink the grid and allow
        // the legend to overflow the container.
        legend: {
            show: true,
            placement: 'outsideGrid'
        },
        */
        axes: 
        {
            // Use a category axis on the x axis and use our custom ticks.
            xaxis: 
            {
                renderer: $.jqplot.CategoryAxisRenderer,
                ticks: ticks
            },
            // Pad the y axis just a little so bars can get close to, but
            // not touch, the grid boundaries.  1.2 is the default padding.
            yaxis: 
            {
                padMin: 0,
                tickOptions: {formatString: '%d'}
            }
        }
    });
});
  </script>
   </strong>

  <% respcount = 0 %>
  <% totcount = 0.0 %>
      <% @responses.each do |counts| %>
        <% if counts.question_id == question.id %>
         <% totcount += 1 %>
       <% end %>
     <% end %>

    <% @answers.each do |ans| %>
      <% if ans.question_id == question.id then %>
        <% respcount += 1 %>
        <p style="margin-left: 100px;"><%= respcount %> : <%= ans.answer_text %>   | Responses - 
        <% intcount = 0 %>
      <% @responses.each do |resp| %>
        <% if resp.question_id == question.id %>
         <% intcount += 1 if resp.answer.to_i == respcount %>
        <% end %>
      <% end %>
      <%= intcount %> | <strong>
      <% if totcount > 0 %>
        <% perc = (100*intcount/totcount).to_i %>
        <%= perc %>%
       <% else %>
         <% perc=0 %> 0%
       <% end %>
     </strong> </p><div style="margin-left: 100px; width:600px; height:20px; background-color:#FFFF00;"><div style="width:<%= perc %>%; height:20px;background-color:#FF9900; border-right:1px #FFF solid;"></div></div>     
     <% end %>
  <% end %>
   <hr />
  <% end %>

<%= link_to 'Go to the List of Questions', root_url %>

app/views/responses/new.html.erb
<h1>New response</h1>

<%= render 'form' %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @response.question.question_text %>
</p>

<p>
  <b>Chosen Answer:</b>
  <%= @response.answer %>
</p>

<p>
  <b>Answered by:</b>
  <%= @response.user.name %>
</p>



<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %> |
<%= link_to 'Show Results', :controller => "responses", :action => "list" %>| 
<%= link_to 'Back to Questions', root_url %>